### ISSUE TITLE
Add Delphin_IDs to sampling entry

### ISSUE THREAD

**Issue by ocni-dtu** [ribuild/delphin_6_automation#84]
https://github.com/ribuild/delphin_6_automation/blob/f44c1c0fda5791a4cea0fb81dd979a9ae9808ed4/delphin_6_automation/database_interactions/sampling_interactions.py#L52-L56

**Comment by Sibjar** [comment]
Test function req. update. Currently no sample.

**Comment by Sibjar** [comment]
https://github.com/ribuild/delphin_6_automation/blob/cc0845546f7990e6b3efc8f472d3f59773763c73/delphin_6_automation/pytest/test_sampling.py#L42-L50
